version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/elb-test
  - source: /index.html
    destination: /var/www/html/
hooks:
  
  ApplicationStop:
    - location: deregister_from_elb.sh
    - location: stop_httpd.sh
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_httpd.sh
    - location: register_with_elb.sh
